Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1       V         -14.17           -9.41 
      2       B           5.72            3.80 
      3       B           5.72            3.80 

Madelung Energy (eV)    -13.15           -5.80 
