Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Mo          -9.28           -5.98 
      2       B           3.41            2.20 
      3       B           3.41            2.20 

Madelung Energy (eV)     -5.83           -2.42 
