Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1       V         -14.18           -9.42 
      2       B           5.73            3.81 
      3       B           5.72            3.80 

Madelung Energy (eV)    -13.18           -5.82 
