Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Mo          -9.29           -5.99 
      2       B           3.42            2.20 
      3       B           3.42            2.20 

Madelung Energy (eV)     -5.84           -2.43 
